"""Added interested_count to Product

Revision ID: 1e1534655d03
Revises: f7dbcee3bf2d
Create Date: 2025-03-31 00:29:24.176178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1534655d03'
down_revision = 'f7dbcee3bf2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interested_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('interested_count')

    # ### end Alembic commands ###
