"""Added is_read column to messages

Revision ID: 38b573eef4d7
Revises: d05f554d88d8
Create Date: 2025-03-28 13:51:29.641479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38b573eef4d7'
down_revision = 'd05f554d88d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('messages_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('messages_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('messages_ibfk_1', 'user', ['sender_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('messages_ibfk_2', 'user', ['receiver_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
