"""Added seen field to Interest model

Revision ID: 78245b04023d
Revises: 636b725400bf
Create Date: 2025-03-31 03:06:44.506917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78245b04023d'
down_revision = '636b725400bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seen', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.drop_column('seen')

    # ### end Alembic commands ###
